steps:
- name: 'python:3.8'
  entrypoint: python3
  args: ['-m', 'pip', 'install', '-t', '.', '-r', 'requirements.txt']
  env:
  - 'TRANSLATOR_SECRET_KEY=$_TRANSLATOR_SECRET_KEY'
- name: 'python:3.8'
  entrypoint: python3
  args: ['./manage.py', 'collectstatic', '--noinput']
substitutions:
  _TRANSLATOR_SECRET_KEY: ''
options:
    env:
    - TRANSLATOR_SECRET_KEY='$_TRANSLATOR_SECRET_KEY'