steps:
- name: 'python:3.8'
  entrypoint: python3
  args: ['-m', 'pip', 'install', '-t', '.', '-r', 'requirements.txt']
  env:
  - 'SECRET_KEY=$_SECRET_KEY'
- name: 'python:3.8'
  entrypoint: python3
  args: ['./manage.py', 'collectstatic', '--noinput']